# Generated by Django 3.2.3 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210610_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='jnjnjnjnj', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='jnjnjnjnj', max_length=200, null=True),
        ),
    ]
